# Generated by Django 2.1.5 on 2019-08-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='product',
        ),
    ]
